In [ ]:
import sys
import platform
import os

In [ ]:
# environment check

print("Python Version:", sys.version)
print("Platform", platform.platform())
print("Working Directory:", os.getcwd())

print("\nEnivonment checked completed.")

Python Version: 3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
Platform Linux-6.6.122+-x86_64-with-glibc2.39
Working Directory: /content

Enivonment checked completed.

In [ ]:
# Check the current environment

import pandas as pd
import numpy as np
import matplotlib
import sklearn

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Scikit-learn:", sklearn.__version__)

print("\nCore data-science libraries are ready.")

Pandas: 2.2.3
NumPy: 2.1.3
Matplotlib: 3.10.0
Scikit-learn: 1.6.1

Core data-science libraries are ready.

In [ ]:
# Verify that data analysis works
import pandas as pd

sample_data = {
    "month": ["January", "February", "March", "April", "May"],
    "sales": [12000, 14500, 32000, 22000, 41000],
    "orders": [120, 135, 129, 150, 172]
}

df = pd.DataFrame(sample_data)

print("Dataset shape:", df.shape)

print("\nDataset overview:", df.head())

print("\nMissing vals:", df.isnull().sum())

print("\nSummary statistics:")
display(df[["sales", "orders"]].describe())

Dataset shape: (5, 3)

Dataset overview:       month  sales  orders
0   January  12000     120
1  February  14500     135
2     March  32000     129
3     April  22000     150
4       May  41000     172

Missing vals: month     0
sales     0
orders    0
dtype: int64

Summary statistics:

              sales      orders
count      5.000000    5.000000
mean   24300.000000  141.200000
std    12153.188882   20.388722
min    12000.000000  120.000000
25%    14500.000000  129.000000
50%    22000.000000  135.000000
75%    32000.000000  150.000000
max    41000.000000  172.000000

In [ ]:
# Mount Google Drive

from google.colab import drive
drive.mount('/content/drive')

# Create and verify the project folders

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

required_folders = [
    "notebooks",
    "data",
    "src",
    "tests",
    "reports",
    "artifacts",
    "docs",
]

PROJECT_ROOT.mkdir(parents=True, exist_ok=True)

for folder in required_folders:
    (PROJECT_ROOT / folder).mkdir(
        parents=True,
        exist_ok=True
    )

print("Project root:", PROJECT_ROOT)
print("Project root exists:", PROJECT_ROOT.exists())
print("\nFolder verification:")

for folder in required_folders:
    path = PROJECT_ROOT / folder
    print(f"{folder}: {path.is_dir()}")

Project root: /content/drive/MyDrive/AI_Data_Scientist_Agent
Project root exists: True

Folder verification:
notebooks: True
data: True
src: True
tests: True
reports: True
artifacts: True
docs: True

In [ ]:
# Create the initial requirements file
from pathlib import Path

requirements = """panads
numpy
matplotlib
scikit-learn
"""

requirement_path = PROJECT_ROOT / "requirements.txt"
requirement_path.write_text(requirements, encoding="utf-8")

print(requirement_path.read_text(encoding="utf-8"))
print("requirement path exist:", requirement_path.exists())

panads
numpy
matplotlib
scikit-learn

requirement path exist: True

In [ ]:
# Verify that the sample analysis still works
import pandas as pd

df = pd.DataFrame({
    "Age": [22, 25, 28, 30, 35],
    "Experience": [0, 2, 4, 6, 10],
    "Salary": [25000, 32000, 45000, 55000, 80000]
})

assert df.shape == (5, 3)
assert df.isnull().sum().sum() == 0
assert df["Salary"].sum() == 237000

print("Dataset validation: PASSED")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Average salary:", df["Salary"].mean())

Dataset validation: PASSED
Rows: 5
Columns: 3
Average salary: 47400.0

# Create a project README

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

readme_content = """# AI Data Scientist Agent

An AI-powered data analysis assistant that aims to help users
inspect datasets, identify data-quality issues, generate insights,
visualize patterns, and build machine learning models.

## Project Goals

- Automated dataset profiling
- Data-quality checks
- Evidence-based analytical summaries
- Exploratory data analysis and visualizations
- Machine learning training and evaluation
- AI-assisted explanations grounded in computed results

## Technology Stack

- Python
- Pandas and NumPy
- Matplotlib
- Scikit-learn
- Google Colab for initial development

Additional tools will be evaluated and added as the project develops.

## Project Status

Phase 1: Environment and project setup.

## Disclaimer

This project is under development. Features and evaluation results
will be documented after they have been implemented and tested.
"""

readme_path = PROJECT_ROOT / "README.md"
readme_path.write_text(readme_content, encoding="utf-8")

print("README created:", readme_path.exists())
print(readme_path.read_text(encoding="utf-8"))

README created: True
# AI Data Scientist Agent

An AI-powered data analysis assistant that aims to help users
inspect datasets, identify data-quality issues, generate insights,
visualize patterns, and build machine learning models.

## Project Goals

- Automated dataset profiling
- Data-quality checks
- Evidence-based analytical summaries
- Exploratory data analysis and visualizations
- Machine learning training and evaluation
- AI-assisted explanations grounded in computed results

## Technology Stack

- Python
- Pandas and NumPy
- Matplotlib
- Scikit-learn
- Google Colab for initial development

Additional tools will be evaluated and added as the project develops.

## Project Status

Phase 1: Environment and project setup.

## Disclaimer

This project is under development. Features and evaluation results
will be documented after they have been implemented and tested.

In [ ]:
# Verify your project files
from pathlib import Path

for name in ["README.md", "requirements.txt"]:
  path = PROJECT_ROOT / name
  print(f"{name}: {"Found" if path.is_file() else "Missing"} ")

README.md: Found
requirements.txt: Found

In [ ]:
# Check whether Git is available in Colab
import subprocess

result = subprocess.run(
    ["git", "--version"],
    capture_output=True,
    text=True
)

print(result.stdout or result.stderr)
print("Git Available:",result.returncode == 0)

git version 2.43.0

Git Available: True

# Create a .gitignore file

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

gitignore_content = """# Secrets and environment variables
.env
.env.*
!.env.example
secrets.json
credentials.json

# Python
__pycache__/
*.py[cod]
.pytest_cache/
.mypy_cache/
.ruff_cache/

# Virtual environments
.venv/
venv/
env/

# Jupyter temporary files
.ipynb_checkpoints/

# Generated model files and large artifacts
artifacts/*
!artifacts/.gitkeep

# Temporary files
*.log
.DS_Store
Thumbs.db
"""

gitignore_path = PROJECT_ROOT / ".gitignore"
gitignore_path.write_text(
    gitignore_content,
    encoding="utf-8"
)

print("Created:", gitignore_path)
print(gitignore_path.read_text(encoding="utf-8"))

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/.gitignore
# Secrets and environment variables
.env
.env.*
!.env.example
secrets.json
credentials.json

# Python
__pycache__/
*.py[cod]
.pytest_cache/
.mypy_cache/
.ruff_cache/

# Virtual environments
.venv/
venv/
env/

# Jupyter temporary files
.ipynb_checkpoints/

# Generated model files and large artifacts
artifacts/*
!artifacts/.gitkeep

# Temporary files
*.log
.DS_Store
Thumbs.db

In [ ]:
# Verify the files before uploading

from pathlib import Path

for name in [
    "README.md",
    "requirements.txt",
    ".gitignore",
]:
    path = PROJECT_ROOT / name
    print(f"{name}: {'FOUND' if path.is_file() else 'MISSING'}")

print("\nProject root:", PROJECT_ROOT)

README.md: FOUND
requirements.txt: FOUND
.gitignore: FOUND

Project root: /content/drive/MyDrive/AI_Data_Scientist_Agent

# Configure Git identity

In [ ]:
import subprocess

GIT_NAME = "YOUR_GITHUB_USERNAME"
GIT_EMAIL = "YOUR_GOOGLE_EMAIL"

subprocess.run(
    ["git", "config", "--global", "user.name", GIT_NAME],
    check=True
)
subprocess.run(
    ["git", "config", "--global", "user.email", GIT_EMAIL],
    check=True
)

print("Git name:", subprocess.check_output(
    ["git", "config", "--global", "user.name"],
    text=True
).strip())

print("Git email configured:", bool(subprocess.check_output(
    ["git", "config", "--global", "user.email"],
    text=True
).strip()))

In [ ]:
# Initialize the repository
from pathlib import Path
import subprocess

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

def run_git(args):
    result = subprocess.run(
        ["git", *args],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True
    )
    print(result.stdout or result.stderr)
    if result.returncode != 0:
        raise RuntimeError(f"Git command failed: {args}")
    return result.stdout.strip()

print(run_git(["init", "-b", "main"]))
print("Git repository initialized.")

Reinitialized existing Git repository in /content/drive/MyDrive/AI_Data_Scientist_Agent/.git/

Reinitialized existing Git repository in /content/drive/MyDrive/AI_Data_Scientist_Agent/.git/
Git repository initialized.

In [ ]:
# Check which files Git sees

print(run_git(["status", "--short", "--branch"]))

## main
?? notebooks/

## main
?? notebooks/

In [ ]:
# Stage only the initial project files

run_git([
    "add",
    "README.md",
    "requirements.txt",
    ".gitignore"
])

print(run_git(["status", "--short"]))

?? notebooks/

?? notebooks/

In [ ]:
# Create the first commit

# We check if there are staged changes first to avoid Git errors.
status = run_git(["status", "--porcelain"])
staged_changes = any(line.startswith(('A', 'M', 'D', 'R', 'C')) for line in status.splitlines())

if staged_changes:
    run_git([
        "commit",
        "-m",
        "chore: initialize AI Data Scientist Agent project"
    ])
    print("Commit created successfully.")
else:
    print("No staged changes found. Creating an initial commit with --allow-empty instead.")
    run_git([
        "commit",
        "--allow-empty",
        "-m",
        "chore: initialize AI Data Scientist Agent project (initial empty)"
    ])

print(run_git(["log", "-1", "--oneline"]))

?? notebooks/

No staged changes found. Creating an initial commit with --allow-empty instead.
[main 6e8cfae] chore: initialize AI Data Scientist Agent project (initial empty)

6e8cfae chore: initialize AI Data Scientist Agent project (initial empty)

6e8cfae chore: initialize AI Data Scientist Agent project (initial empty)

In [ ]:
# Add the remote and verify it
# YOUR CREATED GIT REPO URL
REPO_URL = "https://github.com/goudalija44-cloud/ai-data-scientist-agent.git"

# Verify the URL before using it
assert REPO_URL.startswith("https://github.com/")
assert REPO_URL.endswith(".git")
assert "goudalija44-cloud" in REPO_URL

print("Repository URL format looks correct.")

Repository URL format looks correct.

In [ ]:
import subprocess

def run_git(args):
    result = subprocess.run(
        ["git", *args],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return result.stdout.strip()

# Add the remote only if one isn't already configured
remotes = run_git(["remote"]).splitlines()

if "origin" not in remotes:
    run_git(["remote", "add", "origin", REPO_URL])
else:
    run_git(["remote", "set-url", "origin", REPO_URL])

print(run_git(["remote", "-v"]))

origin	https://github.com/goudalija44-cloud/ai-data-scientist-agent.git (fetch)
origin	https://github.com/goudalija44-cloud/ai-data-scientist-agent.git (push)

In [ ]:
from getpass import getpass
from pathlib import Path
import os
import subprocess
import uuid

username = input("GitHub username: ").strip()
token = getpass("GitHub token (input hidden): ")

credential_file = Path(f"/tmp/gh-credentials-{uuid.uuid4().hex}")
credential_file.touch(mode=0o600)
os.chmod(credential_file, 0o600)

try:
    credential_text = (
        "protocol=https\n"
        "host=github.com\n"
        f"username={username}\n"
        f"password={token}\n\n"
    )

    subprocess.run(
        ["git", "credential-store", f"--file={credential_file}", "store"],
        input=credential_text,
        text=True,
        check=True,
        capture_output=True
    )

    result = subprocess.run(
        [
            "git",
            "-c", "credential.helper=",
            "-c", f"credential.helper=store --file={credential_file}",
            "push", "-u", "origin", "main"
        ],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        env={**os.environ, "GIT_TERMINAL_PROMPT": "0"}
    )

    print(result.stdout)
    if result.returncode == 0:
        print("SUCCESS: Project pushed to GitHub.")
    else:
        print("Push failed. Error details:")
        print(result.stderr)

finally:
    credential_file.unlink(missing_ok=True)
    token = None
    if "credential_text" in locals():
        credential_text = None

In [ ]:
# Phase 1 — Build the data-analysis engine

import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Data-analysis environment is ready.")

Pandas: 2.2.3
NumPy: 2.1.3
Data-analysis environment is ready.

In [ ]:
# Create a realistic test dataset

sample_data = pd.DataFrame({
    "Customer_ID": [101, 102, 103, 104, 104, 105],
    "Age": [25, 32, np.nan, 45, 45, 29],
    "Monthly_Spend": [1200, 2500, 1800, np.nan, np.nan, 2100],
    "Plan": ["Basic", "Premium", "Basic", "Premium", "Premium", "Basic"]
})

display(sample_data)

print("Dataset created:", sample_data.shape)

   Customer_ID   Age  Monthly_Spend     Plan
0          101  25.0         1200.0    Basic
1          102  32.0         2500.0  Premium
2          103   NaN         1800.0    Basic
3          104  45.0            NaN  Premium
4          104  45.0            NaN  Premium
5          105  29.0         2100.0    Basic

Dataset created: (6, 4)

# Build data_profiler.py

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

SRC_DIR = PROJECT_ROOT  / "src"
SRC_DIR.mkdir(parents=True, exist_ok=True)

profiler_code = '''
import pandas as pd


def profile_dataset(df: pd.DataFrame) -> dict:
    """
    Generate a reliable summary of a Pandas DataFrame.

    Returns dataset dimensions, column types, missing values,
    duplicate-row count, and numerical summaries.
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError("Input must be a pandas DataFrame.")

    if df.empty:
        raise ValueError("Dataset must contain at least one row.")

    missing_counts = df.isna().sum()

    profile = {
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "column_names": df.columns.tolist(),
        "data_types": {
            str(column): str(dtype)
            for column, dtype in df.dtypes.items()
        },
        "missing_values": {
            str(column): int(count)
            for column, count in missing_counts.items()
        },
        "total_missing_values": int(missing_counts.sum()),
        "duplicate_rows": int(df.duplicated().sum()),
        "numerical_summary": {},
        "categorical_summary": {},
    }

    numerical_df = df.select_dtypes(include="number")
    categorical_df = df.select_dtypes(
        include=["object", "category", "bool", "string"]
    )

    if not numerical_df.empty:
        profile["numerical_summary"] = (
            numerical_df.describe().round(2).to_dict()
        )

    for column in categorical_df.columns:
        profile["categorical_summary"][str(column)] = {
            "unique_values": int(df[column].nunique(dropna=True)),
            "most_frequent": (
                str(df[column].mode(dropna=True).iloc[0])
                if not df[column].mode(dropna=True).empty
                else None
            ),
        }

    return profile
'''

profiler_path = SRC_DIR / "data_profiler.py"
profiler_path.write_text(profiler_code, encoding="utf-8")

print("Created:", profiler_path)
print("File Exist:", profiler_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/src/data_profiler.py
File Exist: True

In [ ]:
import sys
import json

if str(SRC_DIR) not in sys.path:
  sys.path.insert(0, str(SRC_DIR))

from data_profiler import profile_dataset

profile = profile_dataset(sample_data)

print(json.dumps(profile, indent=2, default=str))

{
  "rows": 6,
  "columns": 4,
  "column_names": [
    "Customer_ID",
    "Age",
    "Monthly_Spend",
    "Plan"
  ],
  "data_types": {
    "Customer_ID": "int64",
    "Age": "float64",
    "Monthly_Spend": "float64",
    "Plan": "object"
  },
  "missing_values": {
    "Customer_ID": 0,
    "Age": 1,
    "Monthly_Spend": 2,
    "Plan": 0
  },
  "total_missing_values": 3,
  "duplicate_rows": 1,
  "numerical_summary": {
    "Customer_ID": {
      "count": 6.0,
      "mean": 103.17,
      "std": 1.47,
      "min": 101.0,
      "25%": 102.25,
      "50%": 103.5,
      "75%": 104.0,
      "max": 105.0
    },
    "Age": {
      "count": 5.0,
      "mean": 35.2,
      "std": 9.28,
      "min": 25.0,
      "25%": 29.0,
      "50%": 32.0,
      "75%": 45.0,
      "max": 45.0
    },
    "Monthly_Spend": {
      "count": 4.0,
      "mean": 1900.0,
      "std": 547.72,
      "min": 1200.0,
      "25%": 1650.0,
      "50%": 1950.0,
      "75%": 2200.0,
      "max": 2500.0
    }
  },
  "categorical_summary": {
    "Plan": {
      "unique_values": 2,
      "most_frequent": "Basic"
    }
  }
}

In [ ]:
# Verify important results automatically

assert profile["rows"] == 6
assert profile["columns"] == 4
assert profile["total_missing_values"] == 3
assert profile["duplicate_rows"] == 1

assert profile["missing_values"]["Age"] == 1
assert profile["missing_values"]["Monthly_Spend"] == 2

print("PASS: Dataset dimensions are correct.")
print("PASS: Missing values are detected correctly.")
print("PASS: Duplicate rows are detected correctly.")
print("All profiler checks passed!")

PASS: Dataset dimensions are correct.
PASS: Missing values are detected correctly.
PASS: Duplicate rows are detected correctly.
All profiler checks passed!

# Create src/data_quality.py

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)
SRC_DIR = PROJECT_ROOT / "src"
SRC_DIR.mkdir(parents=True, exist_ok=True)

quality_code = '''
import pandas as pd


def check_data_quality(df: pd.DataFrame) -> dict:
    """
    Check common data-quality issues without modifying the dataset.
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError("Input must be a pandas DataFrame.")

    if df.empty:
        raise ValueError("Dataset must contain at least one row.")

    missing = df.isna().sum()
    missing_columns = {
        str(column): int(count)
        for column, count in missing.items()
        if count > 0
    }

    duplicate_count = int(df.duplicated().sum())

    constant_columns = [
        str(column)
        for column in df.columns
        if df[column].nunique(dropna=False) <= 1
    ]

    potential_id_columns = [
        str(column)
        for column in df.columns
        if (
            df[column].notna().all()
            and df[column].is_unique
            and (
                "id" in str(column).lower()
                or str(column).lower().endswith("_key")
            )
        )
    ]

    findings = []

    if missing_columns:
        findings.append({
            "issue": "missing_values",
            "severity": "warning",
            "details": missing_columns,
        })

    if duplicate_count > 0:
        findings.append({
            "issue": "duplicate_rows",
            "severity": "warning",
            "details": {"count": duplicate_count},
        })

    if constant_columns:
        findings.append({
            "issue": "constant_columns",
            "severity": "info",
            "details": {"columns": constant_columns},
        })

    if potential_id_columns:
        findings.append({
            "issue": "potential_identifier_columns",
            "severity": "info",
            "details": {"columns": potential_id_columns},
        })

    return {
        "rows_checked": int(len(df)),
        "columns_checked": int(len(df.columns)),
        "missing_value_columns": missing_columns,
        "duplicate_row_count": duplicate_count,
        "constant_columns": constant_columns,
        "potential_identifier_columns": potential_id_columns,
        "findings": findings,
    }
'''

quality_path = SRC_DIR / "data_quality.py"
quality_path.write_text(quality_code, encoding="utf-8")

print("Created:", quality_path)
print("File exists:", quality_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/src/data_quality.py
File exists: True

In [ ]:
import sys
import json

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from data_quality import check_data_quality

quality_report = check_data_quality(sample_data)

print(json.dumps(quality_report, indent=2))

{
  "rows_checked": 6,
  "columns_checked": 4,
  "missing_value_columns": {
    "Age": 1,
    "Monthly_Spend": 2
  },
  "duplicate_row_count": 1,
  "constant_columns": [],
  "potential_identifier_columns": [],
  "findings": [
    {
      "issue": "missing_values",
      "severity": "warning",
      "details": {
        "Age": 1,
        "Monthly_Spend": 2
      }
    },
    {
      "issue": "duplicate_rows",
      "severity": "warning",
      "details": {
        "count": 1
      }
    }
  ]
}

In [ ]:
# Test the results

assert quality_report["rows_checked"] == 6
assert quality_report["columns_checked"] == 4

assert quality_report["missing_value_columns"] == {
    "Age": 1,
    "Monthly_Spend": 2,
}

assert quality_report["duplicate_row_count"] == 1
# "Customer_ID" is NOT an identifier because it contains duplicate values (e.g. 104)
assert "Customer_ID" not in quality_report["potential_identifier_columns"]
assert len(quality_report["potential_identifier_columns"]) == 0

print("PASS: Dataset dimensions verified.")
print("PASS: Missing values detected.")
print("PASS: Duplicate rows detected.")
print("PASS: Non-unique Customer_ID correctly omitted from identifiers.")
print("All data-quality tests passed!")

PASS: Dataset dimensions verified.
PASS: Missing values detected.
PASS: Duplicate rows detected.
PASS: Non-unique Customer_ID correctly omitted from identifiers.
All data-quality tests passed!

# Build the Numerical Analysis Engine

In [ ]:
# Create src/analysis_engine.py

from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)
SRC_DIR = PROJECT_ROOT / "src"
SRC_DIR.mkdir(parents=True, exist_ok=True)

analysis_code = '''
import pandas as pd


def analyze_dataset(df: pd.DataFrame) -> dict:
    """Calculate verified descriptive statistics and correlations."""

    if not isinstance(df, pd.DataFrame):
        raise TypeError("Input must be a pandas DataFrame.")

    if df.empty:
        raise ValueError("Dataset must contain at least one row.")

    numeric_df = df.select_dtypes(include="number")
    results = {
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "numeric_columns": numeric_df.columns.tolist(),
        "numeric_statistics": {},
        "categorical_statistics": {},
        "correlations": {},
    }

    # Calculate numeric statistics while excluding missing values.
    for column in numeric_df.columns:
        series = numeric_df[column]
        results["numeric_statistics"][str(column)] = {
            "count": int(series.count()),
            "mean": (
                round(float(series.mean()), 4)
                if series.count() else None
            ),
            "median": (
                round(float(series.median()), 4)
                if series.count() else None
            ),
            "min": (
                float(series.min())
                if series.count() else None
            ),
            "max": (
                float(series.max())
                if series.count() else None
            ),
            "standard_deviation": (
                round(float(series.std()), 4)
                if series.count() > 1 else None
            ),
        }

    # Summarize categorical columns.
    categorical_df = df.select_dtypes(
        include=["object", "category", "bool", "string"]
    )

    for column in categorical_df.columns:
        counts = df[column].value_counts(dropna=True)
        results["categorical_statistics"][str(column)] = {
            "unique_values": int(df[column].nunique(dropna=True)),
            "top_value": str(counts.index[0]) if not counts.empty else None,
            "top_value_count": int(counts.iloc[0]) if not counts.empty else 0,
        }

    # Pearson correlations are only calculated between numeric columns.
    if len(numeric_df.columns) >= 2:
        corr = numeric_df.corr(method="pearson")
        results["correlations"] = {
            str(col): {
                str(other): (
                    round(float(corr.loc[col, other]), 4)
                    if pd.notna(corr.loc[col, other]) else None
                )
                for other in corr.columns
            }
            for col in corr.columns
        }

    return results
'''

analysis_path = SRC_DIR / "analysis_engine.py"
analysis_path.write_text(analysis_code, encoding="utf-8")

print("Created:", analysis_path)
print("File exists:", analysis_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/src/analysis_engine.py
File exists: True

In [ ]:
# Analyze your sample dataset

import sys
import json

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from analysis_engine import analyze_dataset

analysis_results = analyze_dataset(sample_data)

print(json.dumps(analysis_results, indent=2, default=str))

{
  "rows": 6,
  "columns": 4,
  "numeric_columns": [
    "Customer_ID",
    "Age",
    "Monthly_Spend"
  ],
  "numeric_statistics": {
    "Customer_ID": {
      "count": 6,
      "mean": 103.1667,
      "median": 103.5,
      "min": 101.0,
      "max": 105.0,
      "standard_deviation": 1.472
    },
    "Age": {
      "count": 5,
      "mean": 35.2,
      "median": 32.0,
      "min": 25.0,
      "max": 45.0,
      "standard_deviation": 9.2844
    },
    "Monthly_Spend": {
      "count": 4,
      "mean": 1900.0,
      "median": 1950.0,
      "min": 1200.0,
      "max": 2500.0,
      "standard_deviation": 547.7226
    }
  },
  "categorical_statistics": {
    "Plan": {
      "unique_values": 2,
      "top_value": "Basic",
      "top_value_count": 3
    }
  },
  "correlations": {
    "Customer_ID": {
      "Customer_ID": 1.0,
      "Age": 0.5047,
      "Monthly_Spend": 0.4276
    },
    "Age": {
      "Customer_ID": 0.5047,
      "Age": 1.0,
      "Monthly_Spend": 0.9907
    },
    "Monthly_Spend": {
      "Customer_ID": 0.4276,
      "Age": 0.9907,
      "Monthly_Spend": 1.0
    }
  }
}

In [ ]:
# Test the calculations

assert analysis_results["rows"] == 6
assert analysis_results["columns"] == 4

age_stats = analysis_results["numeric_statistics"]["Age"]

assert age_stats["count"] == 5
assert age_stats["mean"] == 35.2
assert age_stats["median"] == 32.0

spend_stats = analysis_results["numeric_statistics"]["Monthly_Spend"]

assert spend_stats["count"] == 4
assert spend_stats["mean"] == 1900.0

assert "Plan" in analysis_results["categorical_statistics"]

print("PASS: Dataset dimensions verified.")
print("PASS: Missing values excluded from numeric calculations.")
print("PASS: Numeric statistics verified.")
print("PASS: Categorical statistics generated.")
print("All analysis-engine tests passed!")

PASS: Dataset dimensions verified.
PASS: Missing values excluded from numeric calculations.
PASS: Numeric statistics verified.
PASS: Categorical statistics generated.
All analysis-engine tests passed!

# Create automated tests

Create tests/test_analysis_engine.py

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

TESTS_DIR = PROJECT_ROOT / "tests"
TESTS_DIR.mkdir(parents=True, exist_ok=True)

test_code = '''
import pandas as pd
import pytest

from analysis_engine import analyze_dataset
from data_profiler import profile_dataset
from data_quality import check_data_quality


def test_profiler_counts_rows_columns_and_missing_values():
    df = pd.DataFrame({
        "Age": [20, 30, None],
        "City": ["Thane", "Mumbai", "Thane"],
    })

    result = profile_dataset(df)

    assert result["rows"] == 3
    assert result["columns"] == 2
    assert result["total_missing_values"] == 1


def test_quality_checker_detects_duplicates():
    df = pd.DataFrame({
        "Score": [10, 20, 20],
    })

    result = check_data_quality(df)

    assert result["duplicate_row_count"] == 1


def test_analysis_engine_calculates_mean():
    df = pd.DataFrame({
        "Salary": [20000, 30000, 40000],
    })

    result = analyze_dataset(df)

    assert result["numeric_statistics"]["Salary"]["mean"] == 30000.0


def test_analysis_engine_excludes_missing_values():
    df = pd.DataFrame({
        "Sales": [100, None, 300],
    })

    result = analyze_dataset(df)

    stats = result["numeric_statistics"]["Sales"]

    assert stats["count"] == 2
    assert stats["mean"] == 200.0


def test_empty_dataframe_is_rejected():
    df = pd.DataFrame()

    with pytest.raises(ValueError):
        analyze_dataset(df)
'''

test_path = TESTS_DIR / "test_analysis_engine.py"
test_path.write_text(test_code, encoding="utf-8")

print("Created:", test_path)
print("File exists:", test_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py
File exists: True

In [ ]:
%pip install -q pytest

In [ ]:
# Run the tests
import sys
import pytest

SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
  sys.path.insert(0, str(SRC_DIR))

exit_code = pytest.main([
    "-v",
    "--tb=short",
    str(TESTS_DIR / "test_analysis_engine.py"),
])

print("pytest exit code:", exit_code)

assert exit_code == 0, "Some automated tests failed. Fix them before continuing."
print("SUCCESS: All automated tests passed.")

============================= test session starts ==============================
platform linux -- Python 3.13.16, pytest-8.4.2, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content
plugins: langsmith-0.14.2, typeguard-4.6.0, anyio-4.15.1, platformdirs-4.12.2
collecting ... collected 5 items

drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_profiler_counts_rows_columns_and_missing_values PASSED [ 20%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_quality_checker_detects_duplicates PASSED [ 40%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_analysis_engine_calculates_mean PASSED [ 60%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_analysis_engine_excludes_missing_values PASSED [ 80%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_empty_dataframe_is_rejected PASSED [100%]

============================== 5 passed in 1.89s ===============================
pytest exit code: 0
SUCCESS: All automated tests passed.

# Build the Insights Engine

Create src/insights_engine.py

In [ ]:
from pathlib import Path

insights_code = '''
import pandas as pd


def generate_insights(df: pd.DataFrame) -> dict:
    """
    Generate simple, evidence-backed descriptive insights.
    Does not infer causation or make predictions.
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError("Input must be a pandas DataFrame.")

    if df.empty:
        raise ValueError("Dataset must contain at least one row.")

    insights = []

    # Dataset size
    insights.append({
        "type": "dataset_overview",
        "message": f"Dataset contains {len(df)} rows and {len(df.columns)} columns.",
        "evidence": {
            "rows": int(len(df)),
            "columns": int(len(df.columns)),
        },
    })

    # Missing values
    missing = df.isna().sum()
    for column, count in missing.items():
        if count > 0:
            insights.append({
                "type": "missing_values",
                "message": f"Column '{column}' contains {int(count)} missing values.",
                "evidence": {
                    "column": str(column),
                    "missing_count": int(count),
                    "missing_percentage": round(
                        float(count / len(df) * 100), 2
                    ),
                },
            })

    # Numerical patterns
    numeric_df = df.select_dtypes(include="number")

    for column in numeric_df.columns:
        series = numeric_df[column].dropna()

        if series.empty:
            continue

        if series.nunique() == 1:
            insights.append({
                "type": "constant_numeric_column",
                "message": f"Column '{column}' has only one observed numeric value.",
                "evidence": {
                    "column": str(column),
                    "value": float(series.iloc[0]),
                },
            })
            continue

        mean_value = float(series.mean())
        median_value = float(series.median())

        if mean_value > median_value:
            pattern = "mean_above_median"
        elif mean_value < median_value:
            pattern = "mean_below_median"
        else:
            pattern = "mean_equals_median"

        insights.append({
            "type": "numeric_distribution",
            "message": (
                f"Column '{column}': mean is {mean_value:.2f} "
                f"and median is {median_value:.2f}."
            ),
            "evidence": {
                "column": str(column),
                "count": int(series.count()),
                "mean": round(mean_value, 4),
                "median": round(median_value, 4),
                "pattern": pattern,
                "min": float(series.min()),
                "max": float(series.max()),
            },
        })

    # Duplicate rows
    duplicate_count = int(df.duplicated().sum())
    if duplicate_count:
        insights.append({
            "type": "duplicate_rows",
            "message": f"Dataset contains {duplicate_count} duplicate rows.",
            "evidence": {
                "duplicate_count": duplicate_count,
            },
        })

    return {
        "insight_count": len(insights),
        "insights": insights,
    }
'''

insights_path = PROJECT_ROOT / "src" / "insights_engine.py"
insights_path.write_text(insights_code, encoding="utf-8")

print("Created:", insights_path)
print("File exists:", insights_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/src/insights_engine.py
File exists: True

In [ ]:
# Generate insights from your sample dataset
import pandas as pd
import numpy as np
import sys
import json

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from insights_engine import generate_insights

sample_data = pd.DataFrame({
    "Customer_ID": [101, 102, 103, 104, 104, 105],
    "Age": [25, 32, np.nan, 45, 45, 29],
    "Monthly_Spend": [1200, 2500, 1800, np.nan, np.nan, 2100],
    "Plan": ["Basic", "Premium", "Basic", "Premium", "Premium", "Basic"]
})

insight_report = generate_insights(sample_data)

print(json.dumps(insight_report, indent=2, default=str))

{
  "insight_count": 7,
  "insights": [
    {
      "type": "dataset_overview",
      "message": "Dataset contains 6 rows and 4 columns.",
      "evidence": {
        "rows": 6,
        "columns": 4
      }
    },
    {
      "type": "missing_values",
      "message": "Column 'Age' contains 1 missing values.",
      "evidence": {
        "column": "Age",
        "missing_count": 1,
        "missing_percentage": 16.67
      }
    },
    {
      "type": "missing_values",
      "message": "Column 'Monthly_Spend' contains 2 missing values.",
      "evidence": {
        "column": "Monthly_Spend",
        "missing_count": 2,
        "missing_percentage": 33.33
      }
    },
    {
      "type": "numeric_distribution",
      "message": "Column 'Customer_ID': mean is 103.17 and median is 103.50.",
      "evidence": {
        "column": "Customer_ID",
        "count": 6,
        "mean": 103.1667,
        "median": 103.5,
        "pattern": "mean_below_median",
        "min": 101.0,
        "max": 105.0
      }
    },
    {
      "type": "numeric_distribution",
      "message": "Column 'Age': mean is 35.20 and median is 32.00.",
      "evidence": {
        "column": "Age",
        "count": 5,
        "mean": 35.2,
        "median": 32.0,
        "pattern": "mean_above_median",
        "min": 25.0,
        "max": 45.0
      }
    },
    {
      "type": "numeric_distribution",
      "message": "Column 'Monthly_Spend': mean is 1900.00 and median is 1950.00.",
      "evidence": {
        "column": "Monthly_Spend",
        "count": 4,
        "mean": 1900.0,
        "median": 1950.0,
        "pattern": "mean_below_median",
        "min": 1200.0,
        "max": 2500.0
      }
    },
    {
      "type": "duplicate_rows",
      "message": "Dataset contains 1 duplicate rows.",
      "evidence": {
        "duplicate_count": 1
      }
    }
  ]
}

In [ ]:
# Test the insights

assert insight_report["insight_count"] == len(
    insight_report["insights"]
)

insight_types = {
    item["type"] for item in insight_report["insights"]
}

assert "dataset_overview" in insight_types
assert "missing_values" in insight_types
assert "numeric_distribution" in insight_types
assert "duplicate_rows" in insight_types

missing_findings = [
    item for item in insight_report["insights"]
    if item["type"] == "missing_values"
]

age_finding = next(
    item for item in missing_findings
    if item["evidence"]["column"] == "Age"
)

assert age_finding["evidence"]["missing_count"] == 1
assert age_finding["evidence"]["missing_percentage"] == 16.67

print("PASS: Overview insight generated.")
print("PASS: Missing-value findings verified.")
print("PASS: Numerical findings generated.")
print("PASS: Duplicate-row finding generated.")
print("All insights-engine checks passed!")

PASS: Overview insight generated.
PASS: Missing-value findings verified.
PASS: Numerical findings generated.
PASS: Duplicate-row finding generated.
All insights-engine checks passed!

# Integrate everything into one analysis pipeline

Create src/analysis_pipeline.py

In [ ]:
from pathlib import Path

pipeline_code = '''
import pandas as pd

from data_profiler import profile_dataset
from data_quality import check_data_quality
from analysis_engine import analyze_dataset
from insights_engine import generate_insights


def run_analysis(df: pd.DataFrame) -> dict:
    """
    Run the complete dataset analysis pipeline.

    This function does not modify the input DataFrame.
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError("Input must be a pandas DataFrame.")

    if df.empty:
        raise ValueError("Dataset must contain at least one row.")

    return {
        "status": "success",
        "dataset_profile": profile_dataset(df),
        "data_quality": check_data_quality(df),
        "statistical_analysis": analyze_dataset(df),
        "insights": generate_insights(df),
    }
'''

pipeline_path = PROJECT_ROOT / "src" / "analysis_pipeline.py"
pipeline_path.write_text(pipeline_code, encoding="utf-8")

print("Created:", pipeline_path)
print("File exists:", pipeline_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/src/analysis_pipeline.py
File exists: True

In [ ]:
# Run the complete pipeline

import sys
import json

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from analysis_pipeline import run_analysis

full_report = run_analysis(sample_data)

print(json.dumps(full_report, indent=2, default=str))

{
  "status": "success",
  "dataset_profile": {
    "rows": 6,
    "columns": 4,
    "column_names": [
      "Customer_ID",
      "Age",
      "Monthly_Spend",
      "Plan"
    ],
    "data_types": {
      "Customer_ID": "int64",
      "Age": "float64",
      "Monthly_Spend": "float64",
      "Plan": "object"
    },
    "missing_values": {
      "Customer_ID": 0,
      "Age": 1,
      "Monthly_Spend": 2,
      "Plan": 0
    },
    "total_missing_values": 3,
    "duplicate_rows": 1,
    "numerical_summary": {
      "Customer_ID": {
        "count": 6.0,
        "mean": 103.17,
        "std": 1.47,
        "min": 101.0,
        "25%": 102.25,
        "50%": 103.5,
        "75%": 104.0,
        "max": 105.0
      },
      "Age": {
        "count": 5.0,
        "mean": 35.2,
        "std": 9.28,
        "min": 25.0,
        "25%": 29.0,
        "50%": 32.0,
        "75%": 45.0,
        "max": 45.0
      },
      "Monthly_Spend": {
        "count": 4.0,
        "mean": 1900.0,
        "std": 547.72,
        "min": 1200.0,
        "25%": 1650.0,
        "50%": 1950.0,
        "75%": 2200.0,
        "max": 2500.0
      }
    },
    "categorical_summary": {
      "Plan": {
        "unique_values": 2,
        "most_frequent": "Basic"
      }
    }
  },
  "data_quality": {
    "rows_checked": 6,
    "columns_checked": 4,
    "missing_value_columns": {
      "Age": 1,
      "Monthly_Spend": 2
    },
    "duplicate_row_count": 1,
    "constant_columns": [],
    "potential_identifier_columns": [],
    "findings": [
      {
        "issue": "missing_values",
        "severity": "warning",
        "details": {
          "Age": 1,
          "Monthly_Spend": 2
        }
      },
      {
        "issue": "duplicate_rows",
        "severity": "warning",
        "details": {
          "count": 1
        }
      }
    ]
  },
  "statistical_analysis": {
    "rows": 6,
    "columns": 4,
    "numeric_columns": [
      "Customer_ID",
      "Age",
      "Monthly_Spend"
    ],
    "numeric_statistics": {
      "Customer_ID": {
        "count": 6,
        "mean": 103.1667,
        "median": 103.5,
        "min": 101.0,
        "max": 105.0,
        "standard_deviation": 1.472
      },
      "Age": {
        "count": 5,
        "mean": 35.2,
        "median": 32.0,
        "min": 25.0,
        "max": 45.0,
        "standard_deviation": 9.2844
      },
      "Monthly_Spend": {
        "count": 4,
        "mean": 1900.0,
        "median": 1950.0,
        "min": 1200.0,
        "max": 2500.0,
        "standard_deviation": 547.7226
      }
    },
    "categorical_statistics": {
      "Plan": {
        "unique_values": 2,
        "top_value": "Basic",
        "top_value_count": 3
      }
    },
    "correlations": {
      "Customer_ID": {
        "Customer_ID": 1.0,
        "Age": 0.5047,
        "Monthly_Spend": 0.4276
      },
      "Age": {
        "Customer_ID": 0.5047,
        "Age": 1.0,
        "Monthly_Spend": 0.9907
      },
      "Monthly_Spend": {
        "Customer_ID": 0.4276,
        "Age": 0.9907,
        "Monthly_Spend": 1.0
      }
    }
  },
  "insights": {
    "insight_count": 7,
    "insights": [
      {
        "type": "dataset_overview",
        "message": "Dataset contains 6 rows and 4 columns.",
        "evidence": {
          "rows": 6,
          "columns": 4
        }
      },
      {
        "type": "missing_values",
        "message": "Column 'Age' contains 1 missing values.",
        "evidence": {
          "column": "Age",
          "missing_count": 1,
          "missing_percentage": 16.67
        }
      },
      {
        "type": "missing_values",
        "message": "Column 'Monthly_Spend' contains 2 missing values.",
        "evidence": {
          "column": "Monthly_Spend",
          "missing_count": 2,
          "missing_percentage": 33.33
        }
      },
      {
        "type": "numeric_distribution",
        "message": "Column 'Customer_ID': mean is 103.17 and median is 103.50.",
        "evidence": {
          "column": "Customer_ID",
          "count": 6,
          "mean": 103.1667,
          "median": 103.5,
          "pattern": "mean_below_median",
          "min": 101.0,
          "max": 105.0
        }
      },
      {
        "type": "numeric_distribution",
        "message": "Column 'Age': mean is 35.20 and median is 32.00.",
        "evidence": {
          "column": "Age",
          "count": 5,
          "mean": 35.2,
          "median": 32.0,
          "pattern": "mean_above_median",
          "min": 25.0,
          "max": 45.0
        }
      },
      {
        "type": "numeric_distribution",
        "message": "Column 'Monthly_Spend': mean is 1900.00 and median is 1950.00.",
        "evidence": {
          "column": "Monthly_Spend",
          "count": 4,
          "mean": 1900.0,
          "median": 1950.0,
          "pattern": "mean_below_median",
          "min": 1200.0,
          "max": 2500.0
        }
      },
      {
        "type": "duplicate_rows",
        "message": "Dataset contains 1 duplicate rows.",
        "evidence": {
          "duplicate_count": 1
        }
      }
    ]
  }
}

In [ ]:
# Verify the integrated report

assert full_report["status"] == "success"

assert set(full_report.keys()) == {
    "status",
    "dataset_profile",
    "data_quality",
    "statistical_analysis",
    "insights",
}

assert full_report["dataset_profile"]["rows"] == 6
assert full_report["dataset_profile"]["columns"] == 4

assert full_report["data_quality"]["duplicate_row_count"] == 1
assert full_report["data_quality"]["missing_value_columns"] == {
    "Age": 1,
    "Monthly_Spend": 2,
}

assert (
    full_report["statistical_analysis"]
    ["numeric_statistics"]["Age"]["mean"]
    == 35.2
)

assert full_report["insights"]["insight_count"] > 0

print("PASS: All four modules integrated.")
print("PASS: Data-quality results verified.")
print("PASS: Statistical results verified.")
print("PASS: Evidence-backed insights included.")
print("All pipeline checks passed!")

PASS: All four modules integrated.
PASS: Data-quality results verified.
PASS: Statistical results verified.
PASS: Evidence-backed insights included.
All pipeline checks passed!

In [ ]:
# Check that the original data remains unchanged

before = sample_data.copy(deep=True)

run_analysis(sample_data)

pd.testing.assert_frame_equal(sample_data, before)

print("PASS: Analysis did not modify the original dataset.")

PASS: Analysis did not modify the original dataset.

# Build a safe CSV data loader

Create src/data_loader.py

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

loader_code = '''
from pathlib import Path
import pandas as pd

MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024  # 50 MB

def load_csv(file_path: str | Path) -> pd.DataFrame:
  """Load and validate a CSV file without modifying its contents."""

  path = Path(file_path)

  if not path.exists():
    raise FileNotFoundError(f"File Not Found: {file_path}")

  if not path.is_file():
    raise ValueError("The provided path is not a file.")

  if path.suffix.lower() != '.csv':
    raise ValueError("Only CSV files are supported.")

  if path.stat().st_size > MAX_FILE_SIZE_BYTES:
    raise ValueError("File size exceeds the limit of 50 MB.")

  if path.stat().st_size == 0:
    raise ValueError("File is empty.")


  try:

    df = pd.read_csv(file_path)
  except pd.errors.EmptyDataError as exc:
    raise ValueError("CSV contains no tabular data.") from exc

  except (pd.errors.ParserError, UnicodeDecodeError) as exc:
    raise ValueError("CSV file could not be parsed.") from exc


  if df.empty:
    raise ValueError("CSV contains headers but no data rows.")

  if len(df.columns) == 0:
    raise ValueError("CSV contains no columns.")

  if df.columns.duplicated().any():
    raise ValueError("CSV contains duplicate column names.")

  if any(not str(col).strip() for columns in df.columns):
    raise ValueError("CSV contains an empty column name.")

  return df

'''

loader_path = PROJECT_ROOT / "src"  / "data_loader.py"
loader_path.write_text(loader_code, encoding="utf-8")

print("Created:", loader_path)
print("file exists:", loader_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/src/data_loader.py
file exists: True

In [ ]:
# Create a test CSV file
import pandas as pd
import numpy as np

sample_data = pd.DataFrame({
    "Customer_ID": [101, 102, 103, 104, 104, 105],
    "Age": [25, 32, np.nan, 45, 45, 29],
    "Monthly_Spend": [1200, 2500, 1800, np.nan, np.nan, 2100],
    "Plan": ["Basic", "Premium", "Basic", "Premium", "Premium", "Basic"]
})

DATA_DIR = PROJECT_ROOT / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

csv_path = DATA_DIR / "sample_customers.csv"
sample_data.to_csv(csv_path, index=False)

print("CSV Created:", csv_path)
print("File size:", csv_path.stat().st_size, "bytes")

CSV Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/data/sample_customers.csv
File size: 157 bytes

In [11]:
# Fix data_loader.py first to resolve the NameError 'col'
from pathlib import Path
import sys

PROJECT_ROOT = Path("/content/drive/MyDrive/AI_Data_Scientist_Agent")
SRC_DIR = PROJECT_ROOT / "src"
loader_path = SRC_DIR / "data_loader.py"

# Correcting the typo on line 47 from 'columns' to 'col'
fixed_loader_code = '''
from pathlib import Path
import pandas as pd

MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024  # 50 MB

def load_csv(file_path: str | Path) -> pd.DataFrame:
  """Load and validate a CSV file without modifying its contents."""

  path = Path(file_path)

  if not path.exists():
    raise FileNotFoundError(f"File Not Found: {file_path}")

  if not path.is_file():
    raise ValueError("The provided path is not a file.")

  if path.suffix.lower() != '.csv':
    raise ValueError("Only CSV files are supported.")

  if path.stat().st_size > MAX_FILE_SIZE_BYTES:
    raise ValueError("File size exceeds the limit of 50 MB.")

  if path.stat().st_size == 0:
    raise ValueError("File is empty.")

  try:
    df = pd.read_csv(file_path)
  except pd.errors.EmptyDataError as exc:
    raise ValueError("CSV contains no tabular data.") from exc
  except (pd.errors.ParserError, UnicodeDecodeError) as exc:
    raise ValueError("CSV file could not be parsed.") from exc

  if df.empty:
    raise ValueError("CSV contains headers but no data rows.")

  if len(df.columns) == 0:
    raise ValueError("CSV contains no columns.")

  if df.columns.duplicated().any():
    raise ValueError("CSV contains duplicate column names.")

  if any(not str(col).strip() for col in df.columns):
    raise ValueError("CSV contains an empty column name.")

  return df
'''

loader_path.write_text(fixed_loader_code, encoding="utf-8")

# Reload the module to make sure Python gets the updated version
if 'data_loader' in sys.modules:
    del sys.modules['data_loader']

if str(SRC_DIR) not in sys.path:
  sys.path.insert(0, str(SRC_DIR))

from data_loader import load_csv

loaded_df = load_csv(csv_path)

display(loaded_df)

print("Loaded shape:", loaded_df.shape)
print("Column names:", loaded_df.columns.tolist())

   Customer_ID   Age  Monthly_Spend     Plan
0          101  25.0         1200.0    Basic
1          102  32.0         2500.0  Premium
2          103   NaN         1800.0    Basic
3          104  45.0            NaN  Premium
4          104  45.0            NaN  Premium
5          105  29.0         2100.0    Basic

Loaded shape: (6, 4)
Column names: ['Customer_ID', 'Age', 'Monthly_Spend', 'Plan']

In [ ]:
# Verify that loading preserved the data
import pandas as pd

assert loaded_df.shape == sample_data.shape
assert loaded_df.columns.tolist() == sample_data.columns.tolist()

pd.testing.assert_frame_equal(
    loaded_df.reset_index(drop=True),
    sample_data.reset_index(drop=True),
    check_dtype=True,
)

print("PASS: CSV loaded successfully.")
print("PASS: Rows and Columns preserved.")
print("PASS: Missing values preserved.")
print("PASS: Data types and values preserved.")

PASS: CSV loaded successfully.
PASS: Rows and Columns preserved.
PASS: Missign values preserved.
PASS: Data types and values preserved.

In [14]:
# Analyze the loaded file
import sys
from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/AI_Data_Scientist_Agent")
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from analysis_pipeline import run_analysis

loaded_report = run_analysis(loaded_df)

assert loaded_report["status"] == "success"
assert loaded_report["dataset_profile"]["rows"] == len(sample_data)
assert loaded_report["data_quality"]["duplicate_row_count"] == 1

print("PASS: Real CSV loading and analysis pipeline integrated.")

PASS: Real CSV loading and analysis pipeline integrated.

# Build the end-to-end analysis runner

Create src/run_dataset_analysis.py

In [17]:
from pathlib import Path

runner_code = '''
from pathlib import Path

from data_loader import load_csv
from analysis_pipeline import run_analysis

def analyze_csv_file(file_path: str | Path) -> dict:
  """
  Load a csv file and return a complete analysis report.

  file-loading and analysis errrors are raised to the caller.
  """

  df = load_csv(file_path)
  report = run_analysis(df)

  report["source_file"] = Path(file_path).name
  return report
'''

runner_path = PROJECT_ROOT / "src" / "run_dataset_analysis.py"
runner_path.write_text(runner_code, encoding="utf-8")

print("Created:", runner_path)
print("File exists:", runner_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/src/run_dataset_analysis.py
File exists: True

In [18]:
# Run the entire workflow with one function
import sys
import json

if str(SRC_DIR) not in sys.path:
  sys.path.insert(0, str(SRC_DIR))

from run_dataset_analysis import analyze_csv_file

final_report = analyze_csv_file(csv_path)

print(json.dumps(final_report, indent=2, default=str))

{
  "status": "success",
  "dataset_profile": {
    "rows": 6,
    "columns": 4,
    "column_names": [
      "Customer_ID",
      "Age",
      "Monthly_Spend",
      "Plan"
    ],
    "data_types": {
      "Customer_ID": "int64",
      "Age": "float64",
      "Monthly_Spend": "float64",
      "Plan": "object"
    },
    "missing_values": {
      "Customer_ID": 0,
      "Age": 1,
      "Monthly_Spend": 2,
      "Plan": 0
    },
    "total_missing_values": 3,
    "duplicate_rows": 1,
    "numerical_summary": {
      "Customer_ID": {
        "count": 6.0,
        "mean": 103.17,
        "std": 1.47,
        "min": 101.0,
        "25%": 102.25,
        "50%": 103.5,
        "75%": 104.0,
        "max": 105.0
      },
      "Age": {
        "count": 5.0,
        "mean": 35.2,
        "std": 9.28,
        "min": 25.0,
        "25%": 29.0,
        "50%": 32.0,
        "75%": 45.0,
        "max": 45.0
      },
      "Monthly_Spend": {
        "count": 4.0,
        "mean": 1900.0,
        "std": 547.72,
        "min": 1200.0,
        "25%": 1650.0,
        "50%": 1950.0,
        "75%": 2200.0,
        "max": 2500.0
      }
    },
    "categorical_summary": {
      "Plan": {
        "unique_values": 2,
        "most_frequent": "Basic"
      }
    }
  },
  "data_quality": {
    "rows_checked": 6,
    "columns_checked": 4,
    "missing_value_columns": {
      "Age": 1,
      "Monthly_Spend": 2
    },
    "duplicate_row_count": 1,
    "constant_columns": [],
    "potential_identifier_columns": [],
    "findings": [
      {
        "issue": "missing_values",
        "severity": "warning",
        "details": {
          "Age": 1,
          "Monthly_Spend": 2
        }
      },
      {
        "issue": "duplicate_rows",
        "severity": "warning",
        "details": {
          "count": 1
        }
      }
    ]
  },
  "statistical_analysis": {
    "rows": 6,
    "columns": 4,
    "numeric_columns": [
      "Customer_ID",
      "Age",
      "Monthly_Spend"
    ],
    "numeric_statistics": {
      "Customer_ID": {
        "count": 6,
        "mean": 103.1667,
        "median": 103.5,
        "min": 101.0,
        "max": 105.0,
        "standard_deviation": 1.472
      },
      "Age": {
        "count": 5,
        "mean": 35.2,
        "median": 32.0,
        "min": 25.0,
        "max": 45.0,
        "standard_deviation": 9.2844
      },
      "Monthly_Spend": {
        "count": 4,
        "mean": 1900.0,
        "median": 1950.0,
        "min": 1200.0,
        "max": 2500.0,
        "standard_deviation": 547.7226
      }
    },
    "categorical_statistics": {
      "Plan": {
        "unique_values": 2,
        "top_value": "Basic",
        "top_value_count": 3
      }
    },
    "correlations": {
      "Customer_ID": {
        "Customer_ID": 1.0,
        "Age": 0.5047,
        "Monthly_Spend": 0.4276
      },
      "Age": {
        "Customer_ID": 0.5047,
        "Age": 1.0,
        "Monthly_Spend": 0.9907
      },
      "Monthly_Spend": {
        "Customer_ID": 0.4276,
        "Age": 0.9907,
        "Monthly_Spend": 1.0
      }
    }
  },
  "insights": {
    "insight_count": 7,
    "insights": [
      {
        "type": "dataset_overview",
        "message": "Dataset contains 6 rows and 4 columns.",
        "evidence": {
          "rows": 6,
          "columns": 4
        }
      },
      {
        "type": "missing_values",
        "message": "Column 'Age' contains 1 missing values.",
        "evidence": {
          "column": "Age",
          "missing_count": 1,
          "missing_percentage": 16.67
        }
      },
      {
        "type": "missing_values",
        "message": "Column 'Monthly_Spend' contains 2 missing values.",
        "evidence": {
          "column": "Monthly_Spend",
          "missing_count": 2,
          "missing_percentage": 33.33
        }
      },
      {
        "type": "numeric_distribution",
        "message": "Column 'Customer_ID': mean is 103.17 and median is 103.50.",
        "evidence": {
          "column": "Customer_ID",
          "count": 6,
          "mean": 103.1667,
          "median": 103.5,
          "pattern": "mean_below_median",
          "min": 101.0,
          "max": 105.0
        }
      },
      {
        "type": "numeric_distribution",
        "message": "Column 'Age': mean is 35.20 and median is 32.00.",
        "evidence": {
          "column": "Age",
          "count": 5,
          "mean": 35.2,
          "median": 32.0,
          "pattern": "mean_above_median",
          "min": 25.0,
          "max": 45.0
        }
      },
      {
        "type": "numeric_distribution",
        "message": "Column 'Monthly_Spend': mean is 1900.00 and median is 1950.00.",
        "evidence": {
          "column": "Monthly_Spend",
          "count": 4,
          "mean": 1900.0,
          "median": 1950.0,
          "pattern": "mean_below_median",
          "min": 1200.0,
          "max": 2500.0
        }
      },
      {
        "type": "duplicate_rows",
        "message": "Dataset contains 1 duplicate rows.",
        "evidence": {
          "duplicate_count": 1
        }
      }
    ]
  },
  "source_file": "sample_customers.csv"
}

In [21]:
# test the end-to-end workflow

assert final_report["status"] == "success"
assert final_report["source_file"] == "sample_customers.csv"

assert final_report["dataset_profile"]["rows"] == 6
assert final_report["dataset_profile"]["columns"] == 4

assert final_report["data_quality"]["duplicate_row_count"] == 1
assert final_report["data_quality"]["missing_value_columns"] == {
    "Age": 1,
    "Monthly_Spend": 2,
}

assert final_report["insights"]["insight_count"] > 0

print("PASS: CSV loaded through the end-to-end runner.")
print("PASS: Complete analysis report generated.")
print("PASS: Data-quality findings verified.")
print("PASS: Insights returned.")
print("All end-to-end checks passed!")

PASS: CSV loaded through the end-to-end runner.
PASS: Complete analysis report generated.
PASS: Data-quality findings verified.
PASS: Insights returned.
All end-to-end checks passed!

In [22]:
from io import RawIOBase
# Verify invalid file handling
# ==> This test ensures the runner rejects a missing file rather than silently producing a misleading report.

missing_path = DATA_DIR / "file_that_does_not_exist_csv"

try:
  analyze_csv_file(missing_path)
except FileNotFoundError:
  print("PASS: Missing CSV file rejected correctly.")
else:
  raise AssertionError("Missing file was not rejected.")

PASS: Missing CSV file rejected correctly.

# Expand automated testing for the complete project.

we’ve tested individual analysis functions and the end-to-end CSV workflow. Now we’ll test failure cases too, so the application behaves predictably when users provide invalid files or unexpected data.

Create tests/test_data_loader.py

In [23]:
from pathlib import Path

TESTS_DIR = PROJECT_ROOT / "tests"
TESTS_DIR.mkdir(parents=True, exist_ok=True)

loader_tests = '''
import pandas as pd
import pytest

from data_loader import load_csv
from run_dataset_analysis import analyze_csv_file


def test_load_valid_csv(tmp_path):
    path = tmp_path / "valid.csv"
    pd.DataFrame({
        "Age": [20, 30],
        "Salary": [25000, 40000],
    }).to_csv(path, index=False)

    df = load_csv(path)

    assert df.shape == (2, 2)
    assert df["Age"].tolist() == [20, 30]


def test_missing_file_is_rejected(tmp_path):
    with pytest.raises(FileNotFoundError):
        load_csv(tmp_path / "missing.csv")


def test_non_csv_file_is_rejected(tmp_path):
    path = tmp_path / "data.txt"
    path.write_text("example", encoding="utf-8")

    with pytest.raises(ValueError, match="Only CSV"):
        load_csv(path)


def test_empty_file_is_rejected(tmp_path):
    path = tmp_path / "empty.csv"
    path.write_text("", encoding="utf-8")

    with pytest.raises(ValueError):
        load_csv(path)


def test_headers_without_rows_are_rejected(tmp_path):
    path = tmp_path / "headers_only.csv"
    path.write_text("Age,Salary\\\\n", encoding="utf-8")

    with pytest.raises(ValueError):
        load_csv(path)


def test_end_to_end_analysis(tmp_path):
    path = tmp_path / "customers.csv"
    pd.DataFrame({
        "Age": [20, 30, 30],
        "City": ["Thane", "Mumbai", "Mumbai"],
    }).to_csv(path, index=False)

    report = analyze_csv_file(path)

    assert report["status"] == "success"
    assert report["source_file"] == "customers.csv"
    assert report["dataset_profile"]["rows"] == 3
    assert report["data_quality"]["duplicate_row_count"] == 1
'''

test_path = TESTS_DIR / "test_data_loader.py"
test_path.write_text(loader_tests, encoding="utf-8")

print("Created:", test_path)
print("File exists:", test_path.exists())

Created: /content/drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py
File exists: True

In [24]:
# Run both test files

import sys
import pytest

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

exit_code = pytest.main([
    "-v",
    "--tb=short",
    str(TESTS_DIR / "test_analysis_engine.py"),
    str(TESTS_DIR / "test_data_loader.py"),
])

print("Pytest exit code:", exit_code)
assert exit_code == 0, "Some tests failed."
print("SUCCESS: All selected automated tests passed.")

============================= test session starts ==============================
platform linux -- Python 3.13.16, pytest-8.4.2, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content
plugins: langsmith-0.14.2, typeguard-4.6.0, anyio-4.15.1, platformdirs-4.12.2
collecting ... collected 11 items

drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_profiler_counts_rows_columns_and_missing_values PASSED [  9%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_quality_checker_detects_duplicates PASSED [ 18%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_analysis_engine_calculates_mean PASSED [ 27%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_analysis_engine_excludes_missing_values PASSED [ 36%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_empty_dataframe_is_rejected PASSED [ 45%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_load_valid_csv PASSED [ 54%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_missing_file_is_rejected PASSED [ 63%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_non_csv_file_is_rejected PASSED [ 72%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_empty_file_is_rejected PASSED [ 81%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_headers_without_rows_are_rejected PASSED [ 90%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_end_to_end_analysis PASSED [100%]

============================== 11 passed in 0.70s ==============================
Pytest exit code: 0
SUCCESS: All selected automated tests passed.

# Prepare the project for VS Code.

Update requirements.txt

In [25]:
from pathlib import Path

requirements = """pandas
numpy
matplotlib
scikit-learn
pytest
"""

requirements_path = PROJECT_ROOT / "requirements.txt"
requirements_path.write_text(requirements, encoding="utf-8")

print(requirements_path.read_text())

pandas
numpy
matplotlib
scikit-learn
pytest

Create a project structure report

In [26]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

expected_files = [
    "README.md",
    "requirements.txt",
    ".gitignore",
    "src/data_profiler.py",
    "src/data_quality.py",
    "src/analysis_engine.py",
    "src/insights_engine.py",
    "src/analysis_pipeline.py",
    "src/data_loader.py",
    "src/run_dataset_analysis.py",
    "tests/test_analysis_engine.py",
    "tests/test_data_loader.py",
    "data/sample_customers.csv",
]

missing_files = []

for relative_path in expected_files:
    path = PROJECT_ROOT / relative_path
    status = "OK" if path.is_file() else "MISSING"
    print(f"{status}: {relative_path}")

    if not path.is_file():
        missing_files.append(relative_path)

assert not missing_files, f"Missing files: {missing_files}"

print("\nPASS: All expected project files exist.")

OK: README.md
OK: requirements.txt
OK: .gitignore
OK: src/data_profiler.py
OK: src/data_quality.py
OK: src/analysis_engine.py
OK: src/insights_engine.py
OK: src/analysis_pipeline.py
OK: src/data_loader.py
OK: src/run_dataset_analysis.py
OK: tests/test_analysis_engine.py
OK: tests/test_data_loader.py
OK: data/sample_customers.csv

PASS: All expected project files exist.

Run the full test suite one more time

In [27]:
import sys
import pytest

SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

exit_code = pytest.main([
    "-v",
    "--tb=short",
    str(PROJECT_ROOT / "tests"),
])

assert exit_code == 0, "Resolve test failures before moving to VS Code."

print("PASS: Full test suite completed successfully.")

============================= test session starts ==============================
platform linux -- Python 3.13.16, pytest-8.4.2, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content
plugins: langsmith-0.14.2, typeguard-4.6.0, anyio-4.15.1, platformdirs-4.12.2
collecting ... collected 11 items

drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_profiler_counts_rows_columns_and_missing_values PASSED [  9%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_quality_checker_detects_duplicates PASSED [ 18%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_analysis_engine_calculates_mean PASSED [ 27%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_analysis_engine_excludes_missing_values PASSED [ 36%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_analysis_engine.py::test_empty_dataframe_is_rejected PASSED [ 45%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_load_valid_csv PASSED [ 54%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_missing_file_is_rejected PASSED [ 63%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_non_csv_file_is_rejected PASSED [ 72%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_empty_file_is_rejected PASSED [ 81%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_headers_without_rows_are_rejected PASSED [ 90%]
drive/MyDrive/AI_Data_Scientist_Agent/tests/test_data_loader.py::test_end_to_end_analysis PASSED [100%]

============================== 11 passed in 0.27s ==============================
PASS: Full test suite completed successfully.

Save your work to Google Drive

In [28]:
from pathlib import Path

assert PROJECT_ROOT.exists()
assert (PROJECT_ROOT / "src").is_dir()
assert (PROJECT_ROOT / "tests").is_dir()

print("Project root:", PROJECT_ROOT)
print("Source files:", len(list((PROJECT_ROOT / "src").glob("*.py"))))
print("Test files:", len(list((PROJECT_ROOT / "tests").glob("test_*.py"))))
print("Project files are stored in Google Drive.")

Project root: /content/drive/MyDrive/AI_Data_Scientist_Agent
Source files: 7
Test files: 2
Project files are stored in Google Drive.

Create a ZIP of your project in Google Drive

In [ ]:
from pathlib import Path
import zipfile

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Data_Scientist_Agent"
)

ZIP_PATH = Path("/content/AI_Data_Scientist_Agent.zip")

exclude_parts = {
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".ipynb_checkpoints",
    ".venv",
    "venv",
}

with zipfile.ZipFile(
    ZIP_PATH, "w", compression=zipfile.ZIP_DEFLATED
) as archive:
    for path in PROJECT_ROOT.rglob("*"):
        if not path.is_file():
            continue

        relative_path = path.relative_to(PROJECT_ROOT)

        if any(part in exclude_parts for part in relative_path.parts):
            continue

        archive.write(path, relative_path)

print("ZIP created:", ZIP_PATH)
print("ZIP size:", round(ZIP_PATH.stat().st_size / 1024, 2), "KB")
print("ZIP exists:", ZIP_PATH.exists())

In [ ]:
from google.colab import files

files.download("/content/AI_Data_Scientist_Agent.zip")